module.exports = {
  "ALIVE_IMG": "https://i.ibb.co/nr4C5N9/6b180d62431a8564.jpg",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "94776938009",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "OWNER_NUMBER": "94742274855",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
};
